# Generated by Django 3.1.7 on 2021-04-04 23:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Un usuario ya se encuentra registrado con este correo'}, max_length=254, unique=True, verbose_name='email_address')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('is_usuaria', models.BooleanField()),
                ('is_contacto_confianza', models.BooleanField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'PERSONA',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ALERTA',
            },
        ),
        migrations.CreateModel(
            name='GrupoConfianza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=20)),
                ('clave_acceso', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'GRUPO_CONFIANZA',
            },
        ),
        migrations.CreateModel(
            name='Usuaria',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sistema.persona')),
                ('estatura', models.IntegerField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('escolaridad', models.CharField(max_length=30)),
                ('color_cabello', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.colorcabello')),
                ('color_ojo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.colorojos')),
                ('color_piel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.colorpiel')),
                ('complexion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.complexion')),
                ('forma_rostro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.formarostro')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.pais')),
                ('textura_cabello', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.texturacabello')),
                ('tipo_ceja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.tipocejas')),
                ('tipo_nariz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.tiponariz')),
            ],
            options={
                'db_table': 'USUARIA',
            },
            bases=('sistema.persona',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.alerta')),
            ],
            options={
                'db_table': 'UBICACION',
            },
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_confianza', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
                ('autoridad_denuncia', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('violencia', models.CharField(blank=True, max_length=2, null=True)),
                ('acompanar', models.CharField(blank=True, max_length=2, null=True)),
                ('denuncia_previa', models.CharField(blank=True, max_length=2, null=True)),
                ('manejaba_auto', models.CharField(blank=True, max_length=2, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.alerta')),
                ('circunstancia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.circunstancia')),
                ('lazo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.lazo')),
            ],
            options={
                'db_table': 'CUESTIONARIO',
            },
        ),
        migrations.AddField(
            model_name='alerta',
            name='grupo_confianza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.grupoconfianza'),
        ),
        migrations.CreateModel(
            name='GrupoConfianzaHasContactoConfianza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_confianza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo_confianza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.grupoconfianza')),
            ],
            options={
                'db_table': 'GRUPO_CONFIANZA_HAS_CONTACTO_CONFIANZA',
                'unique_together': {('grupo_confianza', 'contacto_confianza')},
            },
        ),
        migrations.AddField(
            model_name='grupoconfianza',
            name='usuaria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema.usuaria'),
        ),
        migrations.CreateModel(
            name='DispositivoRastreador',
            fields=[
                ('numero_serie', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('pin_desactivador', models.IntegerField(blank=True, null=True)),
                ('usuaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.usuaria')),
            ],
            options={
                'db_table': 'DISPOSITIVO_RASTREADOR',
            },
        ),
        migrations.CreateModel(
            name='UsuariaHasSenaUbicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('sena_particular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.senasparticulares')),
                ('ubicacion_corporal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.ubicacioncorporal')),
                ('usuaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.usuaria')),
            ],
            options={
                'db_table': 'USUARIA_HAS_SENA_UBICACION',
                'unique_together': {('ubicacion_corporal', 'sena_particular', 'usuaria')},
            },
        ),
        migrations.CreateModel(
            name='UsuariaHasEnfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.enfermedad')),
                ('usuaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.usuaria')),
            ],
            options={
                'db_table': 'USUARIA_HAS_ENFERMEDAD',
                'unique_together': {('enfermedad', 'usuaria')},
            },
        ),
    ]
